name: CI - Push
on:
  push:
    branches:
      - main
      - dev

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml
    secrets: inherit

  format:
    name: Format
    uses: ./.github/workflows/format.yml
    secrets: inherit

  test:
    name: Test
    uses: ./.github/workflows/test.yml
    secrets: inherit
  
  containerize:
    name: Containerize
    uses: ./.github/workflows/containerize.yml
    secrets: inherit
