name: CI - Release

on:
  push:
    branches:
      - release
  pull_request:
    branches:
      - main

jobs:
  build_format_test:
    uses: ./.github/workflows/ci-build-format-test.yml
    secrets: inherit