name: Containerize

on:
  workflow_call:

jobs:
  containerize:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build the Docker container
        run: docker-compose build --no-cache

      - name: Start the Docker container
        run: docker-compose up -d